# .github/workflows/superlinter.yml
name: Super-Linter

# Controls when the workflow will run
on:
  # Triggers the workflow on push events
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs
jobs:
  # This workflow contains a single job called "super-lint"
  super-lint:
    # Job name
    name: Lint Code Base
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code
        uses: actions/checkout@v3

      # Runs the Super-Linter action
      - name: Run Super-Linter
        uses: github/super-linter@v5
        env:
          # Set the default branch for the repository
          DEFAULT_BRANCH: main
          # Needed to add comments to pull requests
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Optional: Validate Python files
          VALIDATE_PYTHON: true
          # Optional: Validate YAML files
          VALIDATE_YAML: true
